# Generated by Django 5.2.6 on 2025-11-21 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='title',
        ),
        migrations.AddField(
            model_name='chefs',
            name='bio',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefs',
            name='position',
            field=models.CharField(choices=[('Restaurant Ouner', 'Restaurant Ouner'), ('Head Chef', 'Head Chef'), ('Chef', 'Chef')], default='Chef', max_length=100),
        ),
    ]
