# Generated by Django 5.2.6 on 2025-11-21 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='special_requests',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
